[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && daphne promptcraft.asgi:application --bind 0.0.0.0 --port $PORT"
sleepApplication = false
useLegacyStacker = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health/"
healthcheckTimeout = 300

[environments.production]
variables = { DJANGO_SETTINGS_MODULE = "promptcraft.settings.production" }