[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && daphne promptcraft.asgi:application --bind 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/core/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "promptcraft.settings.production"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
DEBUG = "false"