# Generated by Django 4.2.10 on 2025-08-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credittransaction",
            name="org",
        ),
        migrations.AlterUniqueTogether(
            name="featureoverride",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="featureoverride",
            name="org",
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="membership",
            name="org",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="usageevent",
            name="org",
        ),
        migrations.RemoveField(
            model_name="usageevent",
            name="user",
        ),
        migrations.DeleteModel(
            name="BillingEvent",
        ),
        migrations.DeleteModel(
            name="CreditTransaction",
        ),
        migrations.DeleteModel(
            name="FeatureOverride",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.DeleteModel(
            name="UsageEvent",
        ),
    ]
