# Generated by Django 4.2.10 on 2025-06-20 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="templateusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templaterating",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="templates.template",
            ),
        ),
        migrations.AddField(
            model_name="templaterating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="templates.promptfield"
            ),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="templates.template"
            ),
        ),
        migrations.AddField(
            model_name="templatebookmark",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="templates.template",
            ),
        ),
        migrations.AddField(
            model_name="templatebookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarked_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="author",
            field=models.ForeignKey(
                help_text="User who created this template",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="category",
            field=models.ForeignKey(
                help_text="Template category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="templates.templatecategory",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can edit this template",
                related_name="collaborated_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="fields",
            field=models.ManyToManyField(
                help_text="Form fields for this template",
                related_name="templates",
                through="templates.TemplateField",
                to="templates.promptfield",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="related_templates",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related template recommendations",
                to="templates.template",
            ),
        ),
        migrations.AddIndex(
            model_name="promptfield",
            index=models.Index(
                fields=["field_type"], name="prompt_fiel_field_t_e55382_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptfield",
            index=models.Index(
                fields=["is_required"], name="prompt_fiel_is_requ_6a444b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateusage",
            index=models.Index(
                fields=["template", "user"], name="template_us_templat_f392b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateusage",
            index=models.Index(
                fields=["user", "started_at"], name="template_us_user_id_bc6ba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateusage",
            index=models.Index(
                fields=["template", "was_completed"],
                name="template_us_templat_910154_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="templateusage",
            index=models.Index(
                fields=["was_completed", "completed_at"],
                name="template_us_was_com_17c7a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="templaterating",
            index=models.Index(
                fields=["template", "rating"], name="template_ra_templat_8adc15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templaterating",
            index=models.Index(
                fields=["user", "created_at"], name="template_ra_user_id_dfaa9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templaterating",
            index=models.Index(
                fields=["rating", "created_at"], name="template_ra_rating_2defc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templaterating",
            index=models.Index(
                fields=["is_verified", "rating"], name="template_ra_is_veri_822e98_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templaterating",
            unique_together={("template", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="templatefield",
            unique_together={("template", "field")},
        ),
        migrations.AddIndex(
            model_name="templatebookmark",
            index=models.Index(
                fields=["user", "folder_name"], name="template_bo_user_id_d1a4ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templatebookmark",
            index=models.Index(
                fields=["template", "created_at"], name="template_bo_templat_e4ebb9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templatebookmark",
            unique_together={("user", "template")},
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["category", "is_public", "is_active"],
                name="templates_categor_0b569e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["author", "created_at"], name="templates_author__0e5326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["popularity_score"], name="templates_popular_fea1b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["is_featured", "is_public"], name="templates_is_feat_8cf1e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["usage_count"], name="templates_usage_c_c68607_idx"
            ),
        ),
    ]
