# Generated by Django 4.2.10 on 2025-06-21 21:56

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates", "0002_initial"),
    ]

    operations = [
        # Clear existing templates to avoid data conversion issues
        migrations.RunSQL(
            sql="DELETE FROM templates;",
            reverse_sql="-- No reverse operation needed"
        ),
        
        # Drop the existing foreign key constraint
        migrations.RunSQL(
            sql="ALTER TABLE templates DROP CONSTRAINT IF EXISTS templates_author_id_fkey;",
            reverse_sql="-- No reverse operation needed"
        ),
        
        # Drop the existing author_id column
        migrations.RunSQL(
            sql="ALTER TABLE templates DROP COLUMN author_id;",
            reverse_sql="-- No reverse operation needed"
        ),
        
        # Add the new author_id column with UUID type
        migrations.RunSQL(
            sql="ALTER TABLE templates ADD COLUMN author_id UUID;",
            reverse_sql="ALTER TABLE templates DROP COLUMN author_id;"
        ),
          # Create the foreign key constraint pointing to the users table
        migrations.RunSQL(
            sql="ALTER TABLE templates ADD CONSTRAINT templates_author_id_fkey FOREIGN KEY (author_id) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE templates DROP CONSTRAINT templates_author_id_fkey;"
        ),
    ]
