# Generated by Django 4.2.10 on 2025-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0003_fix_author_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="External ID from source (e.g., BS001, MS002)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="performance_metrics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Performance metrics like accuracy, time savings, etc.",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="prompt_framework",
            field=models.CharField(
                blank=True,
                help_text="Framework used (CO-STAR, RACE, CLEAR, APE, STAR)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="subcategory",
            field=models.CharField(
                blank=True,
                help_text="Subcategory within the main category",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="use_cases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of use cases for this template",
            ),
        ),
    ]
