# Generated by Django 4.2.10 on 2025-08-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "templates",
            "0004_template_external_id_template_performance_metrics_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="template",
            name="performance_metrics",
        ),
        migrations.RemoveField(
            model_name="template",
            name="prompt_framework",
        ),
        migrations.RemoveField(
            model_name="template",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="template",
            name="use_cases",
        ),
    ]
