# Generated by Django 4.2.10 on 2025-09-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "templates",
            "0007_template_external_id_template_performance_metrics_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="template_ch_session_b195ab_idx",
            old_name="chat_messag_session_597c4e_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="template_ch_user_id_496bd4_idx",
            old_name="chat_messag_user_id_fc8ba8_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="template_ch_intent__574afc_idx",
            old_name="chat_messag_intent__0f85a4_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="template_ch_respons_c6032f_idx",
            old_name="chat_messag_respons_5d9b3d_idx",
        ),
        migrations.AlterModelTable(
            name="chatmessage",
            table="template_chat_messages",
        ),
    ]
