# Generated by Django 4.2.10 on 2025-06-20 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gamification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userdailychallenge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_challenge_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_unlocks",
                to="gamification.achievement",
            ),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_achievements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dailychallenge",
            index=models.Index(
                fields=["date", "is_active"], name="daily_chall_date_d3745f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailychallenge",
            index=models.Index(
                fields=["challenge_type"], name="daily_chall_challen_277502_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailychallenge",
            unique_together={("date", "challenge_type")},
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["requirement_type"], name="achievement_require_62564f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["is_active", "is_hidden"], name="achievement_is_acti_b2e250_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(fields=["rarity"], name="achievement_rarity_39a6de_idx"),
        ),
        migrations.AddIndex(
            model_name="userdailychallenge",
            index=models.Index(
                fields=["user", "challenge"], name="user_daily__user_id_6260a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdailychallenge",
            index=models.Index(
                fields=["is_completed"], name="user_daily__is_comp_1a57bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdailychallenge",
            index=models.Index(
                fields=["created_at"], name="user_daily__created_48b2e3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdailychallenge",
            unique_together={("user", "challenge")},
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["user", "is_unlocked"], name="user_achiev_user_id_eb0544_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["user", "is_claimed"], name="user_achiev_user_id_888ad5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("user", "achievement")},
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="credit_tran_user_id_c82af7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["transaction_type"], name="credit_tran_transac_0eee54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["related_object_type", "related_object_id"],
                name="credit_tran_related_1da540_idx",
            ),
        ),
    ]
