# Generated by Django 4.2.10 on 2025-06-20 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_custom_fields_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_activity_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="longest_streak",
        ),
        migrations.RemoveField(
            model_name="user",
            name="push_notifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="templates_created_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="templates_used_count",
        ),
        migrations.AlterField(
            model_name="user",
            name="daily_streak",
            field=models.IntegerField(
                default=0,
                help_text="Current daily login streak",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language_preference",
            field=models.CharField(
                default="en", help_text="User's preferred language code", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.IntegerField(
                default=1,
                help_text="User's current level",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                help_text="User's preferred theme",
                max_length=20,
            ),
        ),
    ]
