# Generated by Django 4.2.10 on 2025-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_email_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="provider_id",
            field=models.CharField(
                blank=True,
                help_text="User ID from social provider",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="provider_name",
            field=models.CharField(
                blank=True,
                choices=[("google", "Google"), ("github", "GitHub")],
                help_text="Social authentication provider",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_avatar_url",
            field=models.URLField(
                blank=True, help_text="Avatar URL from social provider", null=True
            ),
        ),
    ]
