# Generated by Django 4.2.10 on 2025-06-20 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_services", "0003_initial"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earned_by",
                to="analytics.badge",
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templatereport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templatereport",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templatereport",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="templates.template",
            ),
        ),
        migrations.AddField(
            model_name="templatefork",
            name="forked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_forks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templatefork",
            name="forked_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fork_source",
                to="templates.template",
            ),
        ),
        migrations.AddField(
            model_name="templatefork",
            name="original_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forks",
                to="templates.template",
            ),
        ),
        migrations.AddField(
            model_name="templatecollaborationrequest",
            name="invited_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaboration_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templatecollaborationrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaboration_requests_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templatecollaborationrequest",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaboration_requests",
                to="templates.template",
            ),
        ),
        migrations.AddField(
            model_name="streaktracker",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streaks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mlmodelprediction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="leaderboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="analytics.leaderboard",
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiprompttemplate",
            name="ai_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_templates",
                to="ai_services.aiprovider",
            ),
        ),
        migrations.AddField(
            model_name="aiprompttemplate",
            name="recommended_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_templates",
                to="ai_services.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="abtestassignment",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="analytics.abtestexperiment",
            ),
        ),
        migrations.AddField(
            model_name="abtestassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ab_test_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usernotificationstatus",
            unique_together={("user", "notification")},
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge")},
        ),
        migrations.AlterUniqueTogether(
            name="templatereport",
            unique_together={("template", "reporter")},
        ),
        migrations.AlterUniqueTogether(
            name="templatecollaborationrequest",
            unique_together={("template", "invited_user")},
        ),
        migrations.AlterUniqueTogether(
            name="streaktracker",
            unique_together={("user", "streak_type")},
        ),
        migrations.AddIndex(
            model_name="mlmodelprediction",
            index=models.Index(
                fields=["model_name", "created_at"],
                name="ml_model_pr_model_n_e97545_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodelprediction",
            index=models.Index(
                fields=["user", "created_at"], name="ml_model_pr_user_id_da5e7e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaderboardentry",
            unique_together={("leaderboard", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="abtestassignment",
            unique_together={("experiment", "user")},
        ),
    ]
