# Generated by Django 4.2.10 on 2025-08-23 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0005_remove_template_external_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "analytics",
            "0003_optimizationhistory_viralcampaign_viraltriggerevent_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("template_view", "Template View"),
                            ("template_usage_start", "Template Usage Start"),
                            ("template_completion", "Template Completion"),
                            ("template_copy", "Template Copy"),
                            ("template_search", "Template Search"),
                            ("category_browse", "Category Browse"),
                            ("user_upgrade", "User Upgrade"),
                            ("user_login", "User Login"),
                            ("user_registration", "User Registration"),
                            ("api_request", "API Request"),
                            ("page_view", "Page View"),
                            ("button_click", "Button Click"),
                            ("form_submission", "Form Submission"),
                            ("error", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                ("page_url", models.URLField(blank=True, max_length=500)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                ("platform", models.CharField(blank=True, max_length=20)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConversionFunnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "funnel_type",
                    models.CharField(
                        choices=[
                            ("registration", "User Registration"),
                            ("first_template_use", "First Template Use"),
                            ("premium_upgrade", "Premium Upgrade"),
                            ("template_completion", "Template Completion"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("steps", models.JSONField(default=list)),
                ("total_entries", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("drop_off_points", models.JSONField(blank=True, default=dict)),
                ("date_range_start", models.DateTimeField()),
                ("date_range_end", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversion_funnels",
            },
        ),
        migrations.CreateModel(
            name="FunnelUserJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("current_step", models.IntegerField(default=0)),
                ("completed_steps", models.JSONField(default=list)),
                ("step_timestamps", models.JSONField(default=dict)),
                ("is_completed", models.BooleanField(default=False)),
                ("dropped_off_at_step", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "funnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_journeys",
                        to="analytics.conversionfunnel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funnel_journeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "funnel_user_journeys",
            },
        ),
        migrations.CreateModel(
            name="TemplateAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_views", models.IntegerField(default=0)),
                ("unique_views", models.IntegerField(default=0)),
                ("views_this_week", models.IntegerField(default=0)),
                ("views_this_month", models.IntegerField(default=0)),
                ("total_uses", models.IntegerField(default=0)),
                ("successful_completions", models.IntegerField(default=0)),
                ("average_completion_time", models.FloatField(default=0.0)),
                ("bookmark_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("copy_count", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("rating_count", models.IntegerField(default=0)),
                ("trending_score", models.FloatField(default=0.0)),
                ("growth_rate", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="templates.template",
                    ),
                ),
            ],
            options={
                "db_table": "template_analytics",
            },
        ),
        migrations.CreateModel(
            name="UserSessionAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("page_views", models.IntegerField(default=0)),
                ("template_views", models.IntegerField(default=0)),
                ("templates_used", models.IntegerField(default=0)),
                ("searches_performed", models.IntegerField(default=0)),
                ("bounce_rate", models.FloatField(blank=True, null=True)),
                ("conversion_events", models.JSONField(blank=True, default=list)),
                ("entry_page", models.URLField(blank=True, max_length=500)),
                ("exit_page", models.URLField(blank=True, max_length=500)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_session_analytics",
            },
        ),
        migrations.RemoveField(
            model_name="optimizationhistory",
            name="user",
        ),
        migrations.DeleteModel(
            name="ViralCampaign",
        ),
        migrations.RemoveField(
            model_name="viralshare",
            name="optimization",
        ),
        migrations.RemoveField(
            model_name="viralshare",
            name="user",
        ),
        migrations.RemoveField(
            model_name="viraltriggerevent",
            name="user",
        ),
        migrations.DeleteModel(
            name="OptimizationHistory",
        ),
        migrations.DeleteModel(
            name="ViralShare",
        ),
        migrations.DeleteModel(
            name="ViralTriggerEvent",
        ),
        migrations.AddIndex(
            model_name="usersessionanalytics",
            index=models.Index(
                fields=["user", "started_at"], name="user_sessio_user_id_70caa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersessionanalytics",
            index=models.Index(
                fields=["session_id"], name="user_sessio_session_6db32c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="funneluserjourney",
            unique_together={("funnel", "user", "session_id")},
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "timestamp"],
                name="analytics_e_event_t_5b2eb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["user", "timestamp"], name="analytics_e_user_id_4d513c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_name", "timestamp"],
                name="analytics_e_event_n_bf27e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["session_id", "timestamp"],
                name="analytics_e_session_b71835_idx",
            ),
        ),
    ]
