# Generated by Django 4.2.16 on 2025-11-23 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=50)),
                ("original_prompt", models.TextField()),
                ("optimized_prompt", models.TextField(blank=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("tokens_input", models.IntegerField(default=0)),
                ("tokens_output", models.IntegerField(default=0)),
                ("credits_spent", models.IntegerField(default=0)),
                ("intent_category", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prompt_history",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="prompt_hist_user_id_cf88a2_idx",
                    ),
                    models.Index(
                        fields=["intent_category"],
                        name="prompt_hist_intent__65b92d_idx",
                    ),
                    models.Index(
                        fields=["is_deleted"], name="prompt_hist_is_dele_9b1dfa_idx"
                    ),
                ],
            },
        ),
    ]
