# Generated by Django 4.2.16 on 2026-02-08 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prompt_history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Conversation title/summary",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of conversation purpose",
                    ),
                ),
                (
                    "total_iterations",
                    models.IntegerField(
                        default=0, help_text="Total number of iterations in this thread"
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        default=0, help_text="Total tokens consumed in this thread"
                    ),
                ),
                (
                    "total_credits",
                    models.IntegerField(
                        default=0, help_text="Total credits spent on this thread"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this thread is shared with others",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversation_threads",
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptIteration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "iteration_number",
                    models.IntegerField(
                        default=1,
                        help_text="Sequential iteration number for this prompt chain",
                    ),
                ),
                (
                    "version_tag",
                    models.CharField(
                        blank=True,
                        help_text="Optional semantic version tag (e.g., 'v1.0', 'draft-2')",
                        max_length=50,
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(help_text="The current iteration of the prompt"),
                ),
                (
                    "system_message",
                    models.TextField(
                        blank=True,
                        help_text="Optional system message for this iteration",
                    ),
                ),
                (
                    "ai_response",
                    models.TextField(
                        blank=True, help_text="AI generated response for this iteration"
                    ),
                ),
                (
                    "response_model",
                    models.CharField(
                        blank=True,
                        help_text="AI model used for this response",
                        max_length=100,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Edit"),
                            ("optimization", "AI Optimization"),
                            ("refinement", "User Refinement"),
                            ("extension", "Extension/Add-on"),
                            ("correction", "Error Correction"),
                            ("experiment", "Experimental Variation"),
                        ],
                        default="manual",
                        help_text="Type of iteration/modification",
                        max_length=50,
                    ),
                ),
                ("tokens_input", models.IntegerField(default=0)),
                ("tokens_output", models.IntegerField(default=0)),
                (
                    "response_time_ms",
                    models.IntegerField(
                        default=0, help_text="Response time in milliseconds"
                    ),
                ),
                ("credits_spent", models.IntegerField(default=0)),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User rating (1-5) for this iteration",
                        null=True,
                    ),
                ),
                (
                    "feedback_notes",
                    models.TextField(
                        blank=True, help_text="User notes about this iteration"
                    ),
                ),
                (
                    "changes_summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of changes from previous iteration",
                    ),
                ),
                (
                    "diff_size",
                    models.IntegerField(
                        default=0,
                        help_text="Character difference from previous iteration",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Model parameters used (temperature, max_tokens, etc.)",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorization and search",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional flexible metadata",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the active/current iteration",
                    ),
                ),
                (
                    "is_bookmarked",
                    models.BooleanField(
                        default=False,
                        help_text="User bookmark for important iterations",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_prompt",
                    models.ForeignKey(
                        help_text="The original prompt this iteration is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iterations",
                        to="prompt_history.prompthistory",
                    ),
                ),
                (
                    "previous_iteration",
                    models.ForeignKey(
                        blank=True,
                        help_text="The previous version in the iteration chain",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_iterations",
                        to="prompt_history.promptiteration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_iterations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prompt_iterations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_order",
                    models.IntegerField(
                        help_text="Order of this message in the thread"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_memberships",
                        to="prompt_history.promptiteration",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="prompt_history.conversationthread",
                    ),
                ),
            ],
            options={
                "db_table": "thread_messages",
                "ordering": ["message_order"],
                "indexes": [
                    models.Index(
                        fields=["thread", "message_order"],
                        name="thread_mess_thread__7761f1_idx",
                    )
                ],
                "unique_together": {("thread", "message_order")},
            },
        ),
        migrations.CreateModel(
            name="SavedPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for the saved prompt", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual prompt text content"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this prompt",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category for organizing prompts (e.g., 'coding', 'writing', 'analysis')",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for searchability and filtering",
                    ),
                ),
                (
                    "use_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this prompt has been used"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this prompt was used",
                        null=True,
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this prompt is marked as favorite",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this prompt is publicly visible to other users",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional flexible metadata (variables, settings, etc.)",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_prompts",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="saved_promp_user_id_feb00a_idx",
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="saved_promp_user_id_33847c_idx",
                    ),
                    models.Index(
                        fields=["user", "is_favorite"],
                        name="saved_promp_user_id_2a2b29_idx",
                    ),
                    models.Index(
                        fields=["is_public", "is_deleted"],
                        name="saved_promp_is_publ_25db6e_idx",
                    ),
                    models.Index(
                        fields=["use_count"], name="saved_promp_use_cou_fc96d8_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="promptiteration",
            index=models.Index(
                fields=["user", "created_at"], name="prompt_iter_user_id_4865ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptiteration",
            index=models.Index(
                fields=["parent_prompt", "iteration_number"],
                name="prompt_iter_parent__6eff1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptiteration",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="prompt_iter_is_acti_5a9998_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptiteration",
            index=models.Index(
                fields=["interaction_type"], name="prompt_iter_interac_f320fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptiteration",
            index=models.Index(
                fields=["is_bookmarked"], name="prompt_iter_is_book_ee6383_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promptiteration",
            unique_together={("parent_prompt", "iteration_number")},
        ),
        migrations.AddIndex(
            model_name="conversationthread",
            index=models.Index(
                fields=["user", "status"], name="conversatio_user_id_4b9636_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationthread",
            index=models.Index(
                fields=["last_activity_at"], name="conversatio_last_ac_cd4b18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationthread",
            index=models.Index(
                fields=["is_shared", "is_deleted"],
                name="conversatio_is_shar_7a0a11_idx",
            ),
        ),
    ]
