# Generated by Django 4.2.10 on 2025-06-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_services", "0001_initial"),
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalizedrecommendation",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="templates.template"
            ),
        ),
    ]
