# Generated by Django 4.2.10 on 2025-06-20 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_services", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalizedrecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiusagequota",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_quota",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="ai_services.aiprovider",
            ),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="ai_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="ai_services.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="related_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_interactions",
                to="templates.template",
            ),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="ai_interaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insights",
                to="ai_services.aiinteraction",
            ),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="related_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_insights",
                to="templates.promptfield",
            ),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="related_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_insights",
                to="templates.template",
            ),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_insights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="personalizedrecommendation",
            index=models.Index(
                fields=["user", "is_viewed", "created_at"],
                name="personalize_user_id_082aa7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personalizedrecommendation",
            index=models.Index(
                fields=["confidence", "expires_at"],
                name="personalize_confide_138ca3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personalizedrecommendation",
            unique_together={("user", "template")},
        ),
        migrations.AlterUniqueTogether(
            name="aimodel",
            unique_together={("provider", "name")},
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["user", "created_at"], name="ai_interact_user_id_b5ffbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["interaction_type", "created_at"],
                name="ai_interact_interac_73c5c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["ai_model", "was_successful"],
                name="ai_interact_ai_mode_127df5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["related_template", "created_at"],
                name="ai_interact_related_820a76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["user", "is_viewed", "created_at"],
                name="ai_insights_user_id_1a4f1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["insight_type", "priority"],
                name="ai_insights_insight_ffa2c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["related_template", "created_at"],
                name="ai_insights_related_2716b9_idx",
            ),
        ),
    ]
