# Generated by Django 4.2.16 on 2025-11-02 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_services", "0004_assistantthread_assistantmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AskMeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intent", models.TextField(help_text="User's original intent/goal")),
                (
                    "spec",
                    models.JSONField(
                        default=dict, help_text="Current prompt specification"
                    ),
                ),
                (
                    "answered_vars",
                    models.JSONField(
                        default=dict, help_text="Variables that have been answered"
                    ),
                ),
                (
                    "current_questions",
                    models.JSONField(
                        default=list, help_text="Current set of questions"
                    ),
                ),
                (
                    "preview_prompt",
                    models.TextField(
                        blank=True, help_text="Preview of the generated prompt"
                    ),
                ),
                (
                    "final_prompt",
                    models.TextField(blank=True, help_text="Final generated prompt"),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("good_enough_to_run", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="askme_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "askme_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AskMeQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qid",
                    models.CharField(
                        help_text="Unique question identifier", max_length=50
                    ),
                ),
                ("title", models.CharField(help_text="Question text", max_length=255)),
                (
                    "help_text",
                    models.TextField(
                        blank=True, help_text="Additional guidance for the user"
                    ),
                ),
                (
                    "variable",
                    models.CharField(
                        help_text="Variable this question maps to", max_length=100
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("short_text", "Short Text"),
                            ("long_text", "Long Text"),
                            ("choice", "Multiple Choice"),
                            ("boolean", "Yes/No"),
                            ("number", "Number"),
                        ],
                        default="short_text",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Options for choice questions",
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("suggested_answer", models.CharField(blank=True, max_length=255)),
                ("answer", models.TextField(blank=True)),
                ("is_answered", models.BooleanField(default=False)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="ai_services.askmesession",
                    ),
                ),
            ],
            options={
                "db_table": "askme_questions",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="askmesession",
            index=models.Index(
                fields=["user", "created_at"], name="askme_sessi_user_id_25d460_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="askmesession",
            index=models.Index(
                fields=["is_complete", "created_at"],
                name="askme_sessi_is_comp_fa87cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="askmequestion",
            index=models.Index(
                fields=["session", "is_answered"], name="askme_quest_session_7357e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="askmequestion",
            index=models.Index(fields=["qid"], name="askme_quest_qid_4f130e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="askmequestion",
            unique_together={("session", "qid")},
        ),
    ]
