# Generated by Django 4.2.16 on 2026-02-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_session_597c4e_idx",
            old_name="chat_msg_session_597c4e_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_role_b6a95d_idx",
            old_name="chat_msg_role_b6a95d_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_contain_178b2e_idx",
            old_name="chat_msg_contain_178b2e_idx",
        ),
    ]
